### PR TITLE
64 bit binary and JNI support rework plus some additional features

### PR DESCRIPTION
**Pull request by blueskyhigh**
Dear grzegok,

recently I decided to replace our Ant based app launcher with a better solution. Launch4j is a convenient solution for most of our requirements, but it was not possible to set VM arguments with place holders (i.e. -Xdump:directory=\\srv\share\%uid_%Y%m%d_%H%M%S_). Since the bug request #145 wa still unresolved, I tried to fix this on my own. This lead me to a few more changes

1. Adaption to MinGW-W64 and GCC-6.3.0
The project's Makefiles didn't work with recent Dev-C++ release. I had to use release Dev-C++ 4.9.9.3 from 2011. After changing a fewl lines of code I managed to do it with MinGW-W64.

2.Integration of native compile in build process
The included Maven pom.xml now uses "Native Maven Plugin" for building object files. To make this more straightforward I moved all sources to one single directory. 

3. 64 bit binary support
Creating 64 bit binarys is only a matter of changing a compile switch -m32 => -m64 and including both binaries. A new targetType property was added to select the appropriate object files. 

4. Merge JNI support in general source

The current JNI implementation contains a few issues which prevented me from using it:

- classpath entries containing spaces cannot be used
- main class name is contained within VM options and is not accepted by IBM JRE
- working directory other than "." is not accepted
- command line args are not handed over to java class
- JNI implementation duplicates code

So I merged the jni* sources into the main source and added a new JNI option to control if JNI is used as launcher. This solves all the above-mentioned issues.

P.S.: I didn't manage to merge the added/removed options to the GUI forms. How can this be done? 

I hope You find these changes useful and I'm looking forward for your response.

Best Regards

blueskyhigh

### CODE REVIEW

**Comment by TheBoegl** [comment]
@blueskyhigh Please create a PR on the original [repository at sourceforge](https://sourceforge.net/p/launch4j/git/). This repo is only a mirror...

**Comment by TheBoegl** [comment]
Let me know if you need help to get your commits to the upstream sourceforge repo.

**Comment by blueskyhigh** [comment]
Dear Sebastian,

it took some time, but I finally committed my changes to the upstrem sf
repo and added a PR.
Not all commits may be usable for the community.

Please let me know if something is missing or should be changed.

Thanks.

blueskyhigh

Let me know if you need help to get your commits to the upstream
sourceforge repo.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/mirror/launch4j/pull/3#issuecomment-298325481>, or mute
the thread

**Comment by TheBoegl** [comment]
Let's see what parts Grzegorz will merge into launch4j. Maybe you could elaborate on his comment on your PR. Anyway thanks for contributing to launch4j.

**Pull request closed without merging**
